### PR TITLE
Bump deps

### PR DESCRIPTION
**Pull request by elcritch**
I updated all the status-im and codex-storage dependencies except nim-stint which breaks after the locked version.  

| Package Name                 | Version   | Commit Hash                             | Lockfile Hash                            |
|------------------------------|-----------|-----------------------------------------|------------------------------------------|
| nim-zlib                     | 0.1.0     | f34ca261efd90f118dc1647beefd2f7a69b05d93 | 74cdeb54b21bededb5a515d36f608bc1850555a2 |
| nim-stew                     | 0.1.0     | 7afe7e3c070758cac1f628e4330109f3ef6fc853 | e18f5a62af2ade7a1fd1d39635d4e04d944def08 |
| nim-http-utils               | 0.3.0     | 3b491a40c60aad9e8d3407443f46f62511e63b18 | e88e231dfcef4585fe3b2fbd9b664dbd28a88040 |
| nim-chronos                  | 3.2.0     | e04c042e8acfe0025c780de8a025aa4c4e042130 | 6525f4ce1d1a7eba146e5f1a53f6f105077ae686 |
| questionable                | 0.10.10   | b3cf35ac450fd42c9ea83dc084f5cba2efc55da3 | 30e4184a99c8c1ba329925912d2c5d4b09acf8cc |
| nim-websock                  | 0.1.0     | 2c3ae3137f3c9cb48134285bd4a47186fa51f0e8 | 7b2ed397d6e4c37ea4df08ae82aeac7ff04cd180 |
| nim-bearssl                  | 0.2.0     | 99fcb3405c55b27cfffbf60f5368c55da7346f23 | f4c4233de453cb7eac0ce3f3ffad6496295f83ab |
| nim-json-serialization       | 0.1.5     | bb53d49caf2a6c6cf1df365ba84af93cdcfa7aa3 | e5b18fb710c3d0167ec79f3b892f5a7a1bc6d1a4 |
| nim-testutils                | 0.5.0     | b56a5953e37fc5117bd6ea6dfa18418c5e112815 | dfc4c1b39f9ded9baf6365014de2b4bfb4dafc34 |
| nim-serialization            | 0.2.0     | 384eb2561ee755446cff512a8e057325848b86a7 | 493d18b8292fc03aa4f835fd825dea1183f97466 |
| nim-faststreams              | 0.3.0     | 720fc5e5c8e428d9d0af618e1e27c44b42350309 | 1b561a9e71b6bdad1c1cdff753418906037e9d09 |
| nim-metrics                  | 0.0.1     | 6142e433fc8ea9b73379770a788017ac528d46ff | 743f81d4f6c6ebf0ac02389f2392ff8b4235bee5 |
| nim-libp2p                  | 1.1.0     | 440461b24b9e66542b34d26a0b908c17f6549d05 | a3e9d1ed80c048cd5abc839cbe0863cefcedc702 |
| nim-chronicles               | 0.10.3    | c9c8e58ec3f89b655a046c485f622f9021c68b61 | 7631f7b2ee03398cb1512a79923264e8f9410af6 |
| nim-protobuf-serialization  | 0.3.0     | 28214b3e40c755a9886d2ec8f261ec48fbb6bec6 | 27b400fdf3bd8ce7120ca66fc1de39d3f1a5804a |

### CODE REVIEW

**Comment by elcritch** [comment]
@dryajov if you wouldn't mind checking this one out as well and verify the important ones (chronos, libp2p) are updated to the versions we want.

**Comment by elcritch** [comment]
Actually we should bump chronos to [0277b65](https://github.com/status-im/nim-chronos/commit/0277b65be2c7a365ac13df002fba6e172be55537). It looks to include the "Asynchronous thread notification mechanism"!

**Comment by elcritch** [comment]
Done! Chronos is now at 0277b65be2c7a365ac13df002fba6e172be55537.

**Review by dryajov — APPROVED** [review]
LGTM!

**Pull request merged**
