### PR TITLE
Remove nimbus build

### PR DESCRIPTION
**Pull request by elcritch**
See https://github.com/codex-storage/nim-codex-dht/issues/71.

### CODE REVIEW

**Comment by elcritch** [comment]
@dryajov do you think a basic Makefile that just runs `nimble test` would be useful?

**Comment by elcritch** [comment]
I tried to get code coverage back but it's still failing.

**Comment by dryajov** [comment]
> I tried to get code coverage back but it's still failing.

Whats the issue? I would not remove it from the CI.

**Comment by elcritch** [comment]
> Whats the issue? I would not remove it from the CI.

@dryajov I believe @yyoncho disabled it to get the Nimble lock working. Looks like he made a PR to re-enable it https://github.com/codex-storage/nim-codex-dht/pull/74.

**Pull request merged**
